import io
import renderer as ren
from flask import Flask, send_file

app = Flask(__name__)

# Send an image (dynamically generated by pillow) to client without saving on disk.
def serve_pil_image(pil_img):
    img_io = io.BytesIO()
    pil_img = pil_img.convert('RGB')
    pil_img.save(img_io, 'JPEG', quality=100)
    img_io.seek(0)
    return send_file(img_io, mimetype='image/jpeg')

# Flask controller to download de image
@app.route('/cards/sales_card.jpeg')
def serve_img():
    img = ren.card_render(
        header="$ 12,041.81", 
        subline="sales yesterday", 
        bolderline="monday", 
        balanceline="19%", 
        density=3
    )
    return serve_pil_image(img)

'''
Run the flask app
export FLASK_APP=server.py && python -m flask run

Go to the url ot get the card image
http://127.0.0.1:5000/cards/sales_card.jpeg
'''